In [1]:
#Si queremos que las imágenes sean mostradas en una ventana emergente quitar el inline
%matplotlib

# OpenCV-Python utiliza NumPy para el manejo de imágenes
import numpy as np
# cv2 es el módulo python para acceder a OpenCV 
import cv2 as cv
# Usamos las poderosas herramientas de graficación de matplotlib para mostrar imágenes, perfiles, histogramas, etc
import matplotlib.pyplot as plt


Using matplotlib backend: MacOSX


In [2]:
# Cargar la imagen color
#-----------------------
img_color = cv.imread('arandelas.png')
imgRGB = cv.cvtColor(img_color, cv.COLOR_BGR2RGB)

plt.figure(1)
plt.imshow(imgRGB)
plt.show()

In [3]:
# Pasamos la imagen a HSV y calculo el color de muestra
#------------------------------------------------------
img_HSV = cv.cvtColor(img_color, cv.COLOR_BGR2HSV)
plt.figure(2)
plt.imshow(img_HSV)

#Elijo la muestra de la arandela naranja
img_muestra_hsv = img_HSV[230:280,230:280,:]

# Calculamos un modelo estadístico sencillo para caracterizar el color de la arandela en el espacio RGB
color_mean, color_std = cv.meanStdDev(img_muestra_hsv)
std = float(color_std[0])
    
print(color_mean)
print(color_std)

[[ 74.2312]
 [197.4364]
 [111.914 ]]
[[0.47428531]
 [4.626657  ]
 [2.35987373]]


In [4]:
# Cómo puedo segmentar el naranja ?
print(img_HSV[217,381,:])

[ 13 176 184]


In [5]:
color_l = (13-3*std,100,100)
color_u = (13+3*std,255,255)

mask = cv.inRange(img_HSV, color_l,  color_u)
img_segmentada = cv.bitwise_and(imgRGB, imgRGB, mask=mask)

plt.figure(3)
plt.imshow(img_segmentada)
plt.show()
